version: '2'

services:
  httpd:
    build: "./httpd"
    ports:
      - "8080:80"
      - "443:443"
    environment:
      WEB_DIR: "Web/"
    volumes:
      - "./app:/usr/local/apache2/htdocs"

  php:
    build: "./php/7.1"
    ports:
      - "9000"
    volumes_from:
      - "httpd"